x-rails_volumes:
  &rails_volumes
  - type: bind
    source: .
    target: /opt/app

services:
  web:
    build:
      target: development
    volumes:
      *rails_volumes
  worker:
    build:
      target: development
    volumes:
      *rails_volumes
  js:
    build:
      context: .
      target: development
    image: ${COMPOSE_PROJECT_NAME}:latest
    volumes:
      *rails_volumes
    command: yarn build --watch
    tty: true
  css:
    build:
      context: .
      target: development
    image: ${COMPOSE_PROJECT_NAME}:latest
    volumes:
      *rails_volumes
    command: yarn build:css --watch
    tty: true
