x-rails-environment:
  &rails_environment
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  REDIS_URL: "redis://redis:6379/1"
  TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
  TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}

x-rails-build:
  &rails_build
  context: .

services:
  web:
    build:
      *rails_build
    ports: 
      - 127.0.0.1:${APP_WEB_PORT:-3000}:3000
    depends_on:
      - db
      - redis
    environment:
      << : *rails_environment
    command: rails server -b 0.0.0.0
  worker:
    build:
      *rails_build
    depends_on:
      - db
      - redis
    environment:
      << : *rails_environment
      QUEUE: default
      VERBOSE: 1
    command: bin/bundle exec sidekiq
  ml:
    build:
      *rails_build
    environment:
      TF_RUN_EAGER_OP_AS_FUNCTION: false
    command: flask --app ml/main run --host=0.0.0.0 --port=5080
    stop_signal: SIGINT
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db:
