x-rails-environment:
  &rails_environment
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  REDIS_URL: "redis://redis:6379/1"
  TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
  TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}

x-rails-build:
  &rails_build
  context: .
  #args:
  #  REDIS_URL: "redis://redis:6379/1"

services:
  web:
    build:
      *rails_build
    image: ${COMPOSE_PROJECT_NAME}:latest
    ports: 
      - "127.0.0.1:${APP_WEB_PORT:-3000}:3000"
    depends_on:
      - db
      - redis
    environment:
      << : *rails_environment
    command: rails server -b 0.0.0.0
    #command: rdbg --open -- bin/rails server -b 0.0.0.0
    ## use with: ./docker_compose exec web rdbg -A
  worker:
    build:
      *rails_build
    image: ${COMPOSE_PROJECT_NAME}:latest
    depends_on:
      - db
      - redis
    environment:
      << : *rails_environment
      QUEUE: default
      VERBOSE: 1
    command: bin/bundle exec sidekiq
    #command: rdbg --open -- bin/bundle exec sidekiq
    ## use with: ./docker_compose exec worker rdbg -A
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db:
